/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth/route'
import { Route as authenticatedRouteImport } from './routes/(authenticated)/route'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as AuthRegisterImport } from './routes/auth/register'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const authenticatedIndexLazyImport = createFileRoute('/(authenticated)/')()
const AuthLoginLazyImport = createFileRoute('/auth/login')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const AuthRouteRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const authenticatedRouteRoute = authenticatedRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => IndexLazyRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const authenticatedIndexLazyRoute = authenticatedIndexLazyImport
  .update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
  .lazy(() =>
    import('./routes/(authenticated)/index.lazy').then((d) => d.Route),
  )

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)

const AuthLoginLazyRoute = AuthLoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteImport
      parentRoute: typeof IndexLazyRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginLazyImport
      parentRoute: typeof AuthRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthRouteImport
    }
    '/(authenticated)/': {
      id: '/(authenticated)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedIndexLazyImport
      parentRoute: typeof authenticatedRouteImport
    }
  }
}

// Create and export the route tree

interface authenticatedRouteRouteChildren {
  authenticatedIndexLazyRoute: typeof authenticatedIndexLazyRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedIndexLazyRoute: authenticatedIndexLazyRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

interface IndexLazyRouteChildren {
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
}

const IndexLazyRouteChildren: IndexLazyRouteChildren = {
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
}

const IndexLazyRouteWithChildren = IndexLazyRoute._addFileChildren(
  IndexLazyRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthRegisterRoute: AuthRegisterRoute,
  AuthLoginLazyRoute: AuthLoginLazyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedIndexLazyRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/': typeof AuthIndexRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutLazyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth': typeof AuthIndexRoute
  '/': typeof authenticatedIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRouteWithChildren
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/about': typeof AboutLazyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/login': typeof AuthLoginLazyRoute
  '/auth/': typeof AuthIndexRoute
  '/(authenticated)/': typeof authenticatedIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/about'
    | '/auth/register'
    | '/auth/login'
    | '/auth/'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/auth/register' | '/auth/login' | '/auth' | '/'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/auth'
    | '/about'
    | '/auth/register'
    | '/auth/login'
    | '/auth/'
    | '/(authenticated)/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx",
      "children": [
        "/(authenticated)"
      ]
    },
    "/(authenticated)": {
      "filePath": "(authenticated)/route.tsx",
      "parent": "/",
      "children": [
        "/(authenticated)/"
      ]
    },
    "/auth": {
      "filePath": "auth/route.tsx",
      "children": [
        "/auth/register",
        "/auth/login",
        "/auth/"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx",
      "parent": "/auth"
    },
    "/auth/login": {
      "filePath": "auth/login.lazy.tsx",
      "parent": "/auth"
    },
    "/auth/": {
      "filePath": "auth/index.tsx",
      "parent": "/auth"
    },
    "/(authenticated)/": {
      "filePath": "(authenticated)/index.lazy.tsx",
      "parent": "/(authenticated)"
    }
  }
}
ROUTE_MANIFEST_END */
