import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsIn, IsOptional, IsString } from 'class-validator';
import { IMAGE_FORMAT_TYPE } from 'src/utils/constants';

export class ImageCdnDto {
  @ApiProperty({
    title: 'token',
    description: 'token of the user. this token is generated by the server',
  })
  @IsString()
  token: string;

  @ApiPropertyOptional({
    title: 'format',
    description: 'format of the image',
  })
  @IsOptional({})
  @IsIn([IMAGE_FORMAT_TYPE.ORIGINAL, IMAGE_FORMAT_TYPE.THUMBNAIL])
  format?: string;

  @ApiPropertyOptional({
    title: 'width',
    description: 'width of the image',
  })
  @IsOptional({})
  width?: number = 100;

  @ApiPropertyOptional({
    title: 'height',
    description: 'height of the image',
  })
  @IsOptional({})
  height?: number = 100;
}
